export function createProject(name) {
  return {
    id: `proj-${Math.random().toString(36).slice(2, 11)}`,
    name,
    createdAt: new Date().toISOString(),
    items: [],
  };
}

export function createItem(fields) {
  return {
    id: `item-${Math.random().toString(36).slice(2, 11)}`,
    title: '',
    url: '',
    retailer: '',
    price: null,
    priceSavedAt: null,
    imageUrl: null,
    status: 'open',
    notes: '',
    ...fields,
  };
}

export const SEED_DATA = [
  {
    id: 'proj-1',
    name: 'Home Office Upgrade',
    createdAt: '2026-05-01T10:30:00Z',
    items: [
      {
        id: 'item-1',
        title: 'Ergonomic Office Chair',
        url: 'https://www.amazon.com/dp/B09V3J2VZ1',
        retailer: 'amazon.com',
        price: 199.99,
        priceSavedAt: '2026-05-01T10:30:00Z',
        imageUrl: null,
        status: 'bought',
        notes: 'Black, lumbar support',
      },
      {
        id: 'item-2',
        title: 'Autonomous SmartDesk Pro',
        url: 'https://www.autonomous.ai/standing-desks/smartdesk-pro',
        retailer: 'autonomous.ai',
        price: 549.00,
        priceSavedAt: '2026-05-02T08:00:00Z',
        imageUrl: null,
        status: 'dropped',
        notes: 'Over budget — revisit Q3',
      },
      {
        id: 'item-3',
        title: 'LG 27UN850-W 27" 4K Monitor',
        url: 'https://www.bestbuy.com/site/searchpage.jsp?st=LG+27UN850+4K+monitor',
        retailer: 'bestbuy.com',
        price: 449.99,
        priceSavedAt: '2026-05-03T12:00:00Z',
        imageUrl: null,
        status: 'open',
        notes: 'USB-C 90W, check stock',
      },
      {
        id: 'item-4',
        title: 'Keychron K2 Wireless Keyboard',
        url: 'https://www.keychron.com/products/keychron-k2-wireless-mechanical-keyboard',
        retailer: 'keychron.com',
        price: 89.00,
        priceSavedAt: '2026-05-04T09:00:00Z',
        imageUrl: null,
        status: 'open',
        notes: 'Hot-swap, red switches',
      },
      {
        id: 'item-5',
        title: 'Elgato Key Light Air',
        url: 'https://www.amazon.com/dp/B082QHRZFW',
        retailer: 'amazon.com',
        price: 99.99,
        priceSavedAt: '2026-05-05T15:00:00Z',
        imageUrl: null,
        status: 'open',
        notes: '',
      },
    ],
  },
  {
    id: 'proj-2',
    name: 'Kitchen Reno',
    createdAt: '2026-05-10T09:00:00Z',
    items: [
      {
        id: 'item-6',
        title: 'Samsung 28 cu ft French Door Refrigerator',
        url: 'https://www.bestbuy.com/site/searchpage.jsp?st=samsung+french+door+refrigerator',
        retailer: 'bestbuy.com',
        price: 1799.99,
        priceSavedAt: '2026-05-10T09:00:00Z',
        imageUrl: null,
        status: 'bought',
        notes: 'Stainless, delivery scheduled May 20',
      },
      {
        id: 'item-7',
        title: 'KitchenAid Artisan Stand Mixer',
        url: 'https://www.target.com/s?searchTerm=kitchenaid+artisan+stand+mixer',
        retailer: 'target.com',
        price: 379.99,
        priceSavedAt: '2026-05-11T10:00:00Z',
        imageUrl: null,
        status: 'dropped',
        notes: 'Not a priority this round',
      },
      {
        id: 'item-8',
        title: 'Caraway Nonstick Cookware Set',
        url: 'https://www.carawayhome.com/products/cookware-set',
        retailer: 'carawayhome.com',
        price: 395.00,
        priceSavedAt: '2026-05-12T11:00:00Z',
        imageUrl: null,
        status: 'open',
        notes: 'Sage color',
      },
      {
        id: 'item-9',
        title: 'Instant Pot Duo 7-in-1',
        url: 'https://www.walmart.com/ip/Instant-Pot-Duo/43877342',
        retailer: 'walmart.com',
        price: 79.00,
        priceSavedAt: '2026-05-13T14:00:00Z',
        imageUrl: null,
        status: 'open',
        notes: '8qt, check price history',
      },
      {
        id: 'item-10',
        title: 'Philips Hue Under Cabinet Lights',
        url: 'https://www.amazon.com/dp/B07PXG9ZD9',
        retailer: 'amazon.com',
        price: 119.99,
        priceSavedAt: '2026-05-14T16:00:00Z',
        imageUrl: null,
        status: 'open',
        notes: 'Need hub or go gradient strip',
      },
    ],
  },
];
